services:
  - type: web
    name: flask-server
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    runtime: python
    pythonVersion: 3.10.12
    region: oregon  # or keep your preferred region
    plan: free
